name: build-and-deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: docker build -t $IMAGE:latest ./astro-site
      - run: docker tag $IMAGE:latest $IMAGE:${GITHUB_SHA::7}
      - run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: |
          docker push $IMAGE:latest
          docker push $IMAGE:${GITHUB_SHA::7}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: >
          aws ssm send-command
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          --document-name AWS-RunShellScript
          --parameters 'commands=["cd ~/openpage","docker compose pull web","docker compose up -d web","docker image prune -f --filter \"until=240h\""]'
          --comment "OpenPage roll-out"
          --output text
